// Top-level build.gradle

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // ✅ Android Gradle Plugin
        classpath "com.android.tools.build:gradle:8.5.2"

    }
}

// ✅ Repositories are handled in settings.gradle

tasks.register("clean", Delete) {
    delete(rootProject.buildDir)
}
