<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class BulkEmployeesAttendanceExport implements FromArray, WithHeadings, WithStyles
{
    protected $data;
    protected $headers;

    // Constructor: Pass attendance data and column headers
    public function __construct(array $data, array $headers, array $extraInfo)
    {
        $this->data = $data;
        $this->headers = $headers; // Store dynamic headers
        $this->extraInfo = $extraInfo;
    }

    // Return the full data set as an array
    public function array(): array
    {
        // return $this->data; // Directly returning structured attendance data

        // Employee details formatted as separate rows
      $exportData = [
        ["Date Range  :  {$this->extraInfo['date_range']}"],
        ["Generated By  :  {$this->extraInfo['generated_by']}"],
        ["Report Date  :  {$this->extraInfo['report_date']}"],
        // ["Employee Name :  {$this->empData['employee_name']}"],
        // ["Employee Code :  {$this->empData['employee_code']}"],
        // ["Designation :  {$this->empData['designation']}"],
        // ["Email :  {$this->empData['email']}"],
        [""], // Empty row for spacing
      ];

      // Append headers and attendance data
      $exportData[] = $this->headers;
      $exportData = array_merge($exportData, $this->data);

      return $exportData;
    }

    // Define column headers for the export
    public function headings(): array
    {
        return [];
    }

    // Apply styling to the headers
    public function styles(Worksheet $sheet)
    {
        $highestColumn = $sheet->getHighestColumn();

        // Apply bold text for employee details
        $sheet->getStyle('A1:A5')->applyFromArray([
          'font' => ['bold' => true],
        ]);


        // Apply bold text & background color for headers
        $sheet->getStyle('A5:' . $highestColumn . '5')->applyFromArray([
            'font' => ['bold' => true],
            'fill' => [
                'fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,
                'startColor' => ['rgb' => 'D9E1F2'], // Light blue background
            ],
        ]);
    }
}
