<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;


class ExportAllRatecards implements FromArray, WithStyles
{
    protected $data;
    protected $headers;
    protected $extraInfo;

    public function __construct(array $data, array $headers, array $ExtraInfo)
    {
        $this->data = $data;
        $this->headers = $headers;
        $this->extraInfo = $ExtraInfo;
    }

    public function array(): array
    {
        $exportData = [
            ["Title  :  {$this->extraInfo['title']}"],
            ["Generated By  :  {$this->extraInfo['generated_by']}"],
            ["Report Date  :  {$this->extraInfo['report_date']}"],
            [""], // Empty row
        ];

        // Append headers and main data
        $exportData[] = $this->headers;
        $exportData = array_merge($exportData, $this->data);

        return $exportData;
    }

    public function styles(Worksheet $sheet)
    {
        $highestColumn = $sheet->getHighestColumn();
        $headerRow = 5; // Since row 4 is where headers start

        // Apply bold to the "Generated By" and "Report Date" rows
        $sheet->getStyle('A1:A4')->applyFromArray([
            'font' => ['bold' => true],
        ]);

        // Apply style to header row
        $sheet->getStyle("A{$headerRow}:{$highestColumn}{$headerRow}")->applyFromArray([
            'font' => ['bold' => true],
            'fill' => [
                'fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,
                'startColor' => ['rgb' => 'D9E1F2'],
            ],
        ]);
    }
}